---
title: "Using Plotly in R-Markdown presented as an HTML Doc"
author: Brandon Miranda
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(tidyverse)
library(dplyr)
library(MASS)
library(quantmod)

```

```{r mtcars, echo=FALSE}
fig1 <- mtcars %>%
  plot_ly(x = ~mpg, y = ~disp)
fig1
```

# Example using layout function
```{r layout, echo=FALSE}
fig1 <- mtcars %>%
  plot_ly(x = ~mpg, y = ~disp) %>%
  layout(
    title = "Miles per Gallon vs Displacement",
    xaxis = list(
      title ="Miles per Gallon",
      range = c(10, 35)
    ),
    yaxis = list(
      title = "Displacement",
      range = c(50, 500)
    )
  )
fig1
```


```{r 2plots, echo=FALSE}
fig1 <- mtcars %>%
  plot_ly(x = ~factor(cyl), y = ~mpg, type = "scatter",
          name = "Scatter") %>%
  add_boxplot(name = "Boxplot")
fig1
```

```{r tracer, echo=FALSE}
fig <- plot_ly(z = ~volcano, type = "heatmap", colorscale='Rainbow')

# chart option buttons
chart_types <- list(
  type = "buttons",
  direction = "right",
  xanchor = 'center',
  yanchor = "top",
  pad = list('r'= 0, 't'= 10, 'b' = 10),
  x = 0.5,
  y = 1.27,
  buttons = list(
    
    list(method = "restyle",
         args = list("type", "heatmap"),
         label = "Heatmap"),
    
    list(method = "restyle",
         args = list("type", "contour"),
         label = "Contour"),
    
    list(method = "restyle",
         args = list("type", "surface"),
         label = "Surface")
  ))

# color option buttons  
color_types <- list(
  type = "buttons",
  direction = "right",
  xanchor = 'center',
  yanchor = "top",
  pad = list('r'= 0, 't'= 10, 'b' = 10),
  x = 0.5,
  y = 1.17,
  buttons = list(
    
    list(method = "restyle",
         args = list("colorscale", "Rainbow"),
         label = "Rainbow"),
    
    list(method = "restyle",
         args = list("colorscale", "Jet"),
         label = "Jet"),
    
    list(method = "restyle",
         args = list("colorscale", "Earth"),
         label = "Earth"),
    
    list(method = "restyle",
         args = list("colorscale", "Electric"),
         label = "Electric")
  ))

annot <- list(list(text = "Chart<br>Type", x=0.2, y=1.25, xref='paper', yref='paper', showarrow=FALSE),
              list(text = "Color<br>Type", x=0.2, y=1.15, xref='paper', yref='paper', showarrow=FALSE))

# plot
fig <- fig %>% layout(
  xaxis = list(domain = c(0.1, 1)),
  yaxis = list(title = "y"),
  updatemenus = list(chart_types,color_types),
  annotations = annot)

fig


```


# Example of using chart option buttons
```{r eruptions, echo=FALSE}
fig <- plot_ly(z = ~volcano, type = "heatmap", colorscale='Rainbow')

# chart option buttons
chart_types <- list(
  type = "buttons",
  direction = "right",
  xanchor = 'center',
  yanchor = "top",
  pad = list('r'= 0, 't'= 10, 'b' = 10),
  x = 0.5,
  y = 1.27,
  buttons = list(
    
    list(method = "restyle",
         args = list("type", "heatmap"),
         label = "Heatmap"),
    
    list(method = "restyle",
         args = list("type", "contour"),
         label = "Contour"),
    
    list(method = "restyle",
         args = list("type", "surface"),
         label = "Surface")
  ))

# color option buttons  
color_types <- list(
  type = "buttons",
  direction = "right",
  xanchor = 'center',
  yanchor = "top",
  pad = list('r'= 0, 't'= 10, 'b' = 10),
  x = 0.5,
  y = 1.17,
  buttons = list(
    
    list(method = "restyle",
         args = list("colorscale", "Rainbow"),
         label = "Rainbow"),
    
    list(method = "restyle",
         args = list("colorscale", "Jet"),
         label = "Jet"),
    
    list(method = "restyle",
         args = list("colorscale", "Earth"),
         label = "Earth"),
    
    list(method = "restyle",
         args = list("colorscale", "Electric"),
         label = "Electric")
  ))

annot <- list(list(text = "Chart<br>Type", x=0.2, y=1.25, xref='paper', yref='paper', showarrow=FALSE),
              list(text = "Color<br>Type", x=0.2, y=1.15, xref='paper', yref='paper', showarrow=FALSE))

# plot
fig <- fig %>% layout(
  xaxis = list(domain = c(0.1, 1)),
  yaxis = list(title = "y"),
  updatemenus = list(chart_types,color_types),
  annotations = annot)

fig
```

# 

